### ISSUE TITLE
-p and -u is not recognized

### ISSUE THREAD

**Issue by predic8** [predic8/activemq-nagios-plugin#1]
```
/opt/nagios-plugins$ ./check_activemq.py health -p admin -u admin 
usage: check_activemq.py [-h] [--host HOST] [--port PORT] [-u USER] [-p PWD]
                         [-j JOLOKIA]
                         {queuesize,health,subscriber} ...
check_activemq.py: error: unrecognized arguments: -p admin -u admin
```

**Comment by r41d** [comment]
The parsing is done with python's argparse package and is organized in subparsers for the three available modes.
The parameters -u and -p are parameters for the root parser because they can be used for any mode.
In this example, the -u and -p parameters are send to to the health-subparser, which doesn't understand them.
This can easily be fixed by putting `health` at the end of the parameter list:
```./check_activemq.py -p admin -u admin health```
